### ISSUE TITLE
Support SURF detection

### ISSUE THREAD

**Issue by minhnguyenlinknode** [TrekDev/Xamarin.Android.OpenCV#13]
Hi,

Your samples work very nice.

One thing is, when I use this:

`var detector = FeatureDetector.Create(FeatureDetector.Surf);`

it throws exception: 

> (Specified feature detector type is not supported.) 

I found this on SO: http://stackoverflow.com/questions/30657774/surf-and-sift-algorithms-doesnt-work-in-opencv-3-0-java

So could you please re-compile `.a` or `so` binding files to support these detections ?

Many thanks,

**Comment by jeremy-ellis-tech** [comment]
Hi, thanks for the feedback. I did consider this when first creating the library but I thought it was a bit bulky already and didn't want to make it any larger. 

Unfortunately I don't have access to a Windows machine at the minute so adding/testing this feature will take some time. I'll definitely look into it when I've got my Windows box up and running again. If you're able to do it before me I'll happily take a pull request.

In the meantime if you're able to run this could you maybe help out these guys here: https://github.com/TrekDev/Xamarin.Android.OpenCV/issues/12 Since I don't have a working Windows machine it's quite hard for me to troubleshoot.

Thanks,

TD

**Comment by RodrigodeMoura** [comment]
hi, @minhnguyenlinknode , like @TrekDev  said can you help me with my issue #12

**Comment by minhnguyenlinknode** [comment]
Hi TrekDev,

I don't know how to build .a files from OpenCV source code and how it works.
If you can tell me how to do it I will try to do it. I am using Xamarin Android for Visual Studio 2015.

Thanks,

**Comment by jeremy-ellis-tech** [comment]
@minhnguyenlinknode First you need to download the OpenCV 3.1.0 source from here: https://github.com/opencv/opencv/archive/3.1.0.zip

Then you'll need to compile the project. Here's a short description on how to do that: http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk

**Comment by jeremy-ellis-tech** [comment]
@minhnguyenlinknode Sorry I probably won't implement this because it isn't included in the default Android OpenCV binaries. Please feel free to fork this though if you feel like people could benefit from including this.

**Comment by minhnguyenlinknode** [comment]
So could you suggest how can I use OpenCV Feature Matching (SURF, SIFT...) with this library?
Thanks,

**Comment by jeremy-ellis-tech** [comment]
Download the OpenCV v3.1.0 source code. Build the OpenCV android target with SURF/SIFT support, you'll end up with the .a files. Then just replace the .a files with the ones in OpenCV.Binding/Jars.

**Comment by minhnguyenlinknode** [comment]
Thanks for your suggestion. I had a look at rebuild opencv to get .a files but the documentation seems not clear to me. I will try again later. Thanks.

**Comment by minhnguyenlinknode** [comment]
Also, where did you get these .a files? Did you build it by yourself?

**Comment by jeremy-ellis-tech** [comment]
I think these were provided in the OpenCV4Android download. I did have to build the ones on the v2.4.11 branch from scratch using the same method.
