### ISSUE TITLE
Is there a Bug in the OpenCV Java Wrapper?

### ISSUE THREAD

**Issue by CeadeS** [TrekDev/Xamarin.Android.OpenCV#4]
I tried to use several feature detectors and got an exception. This exception led me to a post that sais, that there is a bug in the OpenCV 3.0. To fix this OpenCV must be buildt again from source. Here is where i found a solution: http://stackoverflow.com/questions/30657774/surf-and-sift-algorithms-doesnt-work-in-opencv-3-0-java
Is it possible to fix it or switch to Opencv 2.4?

**Comment by jeremy-ellis-tech** [comment]
Hi @CeadeS. These bindings are using the OpenCV libraries built for v3.1 (not v3.0). Are you sure that bug is still present in v3.1? If so I can look into rebuilding them with the fix suggested in that thread, although I may not be able to do this for a while. If you're able to make the changes yourself and send me across the compiled libraries for each ABI, I'll be happy to update them in the repo.

I don't think just switching to v2.4 is an option. IIRC v2.4 has a different interface to v3.0+, so a lot of methods/classes are called something else or missing completely. I could have the v2.4 bindings on a separate branch if you think it would help.

Another option, if the bugs are in the Java wrappers themselves, would be to write your own native C++ which could be called from C# directly, see the face detection and mixed processing in the SDK Demo for examples.

**Comment by CeadeS** [comment]
I receive exact the same exception message for these FeatureDetectors. It may have something to do with the fakt that SIFT and SURF are non-free software. They may be excluded for that reason in all versions newer then 3.

**Comment by jeremy-ellis-tech** [comment]
@CeadeS That's unfortunate. If it's a case that they just haven't included the `.so` files you should be able to compile it for the abi you wish to use and put it in the correct lib folder. Since this isn't a bug with the bindings themselves I'll probably close this issue. Thanks for letting me know anyway.
